"use client";
import React, { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import Userheader from "../../components/Userheader";
import MobileBottomNav from "../../components/MobileBottomNav";

const tabs = [{ label: "Available", href: "/availablecampaigns" }, { label: "Performance", href: "/affiliateperformance" }];
const campaigns = [{ name: "GlowUp Skincare", category: "Beauty", click: "$0.20", conversion: "$12.00", description: "Promote natural skincare products." }, { name: "GlowUp Skincare", category: "Beauty", click: "$0.20", conversion: "$12.00", description: "Promote natural skincare products." }];
export default function Mobilepage() { const [selected, setSelected] = useState(null); const pathname = usePathname(); return <div className="pagecontent gridpagecontent innerpagegrid dashboardpage campaigns-mobile-page"><Userheader /><main className="campaigns-mobile-page__main"><div className="mobile-page-heading"><span>Affiliate pro</span><h1>Available campaigns</h1><p>Choose a campaign and start earning from referrals.</p></div><div className="mobile-segmented-tabs">{tabs.map((tab) => <Link key={tab.label} href={tab.href} className={pathname === tab.href ? "is-active" : ""}>{tab.label}</Link>)}</div><div className="campaigns-mobile-page__filters"><input placeholder="Search campaign" aria-label="Search campaign" /><select aria-label="Campaign category"><option>All categories</option><option>Beauty</option></select></div><section className="campaigns-mobile-page__list">{campaigns.map((campaign, index) => <article key={`${campaign.name}-${index}`}><div className="campaigns-mobile-page__head"><div><span>{campaign.category}</span><h2>{campaign.name}</h2></div><b>Active</b></div><p>{campaign.description}</p><div className="campaigns-mobile-page__payout"><span>Per click<strong>{campaign.click}</strong></span><span>Per conversion<strong>{campaign.conversion}</strong></span></div><button type="button" className="mobile-primary-button" onClick={() => setSelected(campaign)}>Generate tracking link</button></article>)}</section></main><MobileBottomNav />{selected && <div className="mobile-action-sheet" onClick={() => setSelected(null)}><div onClick={(event) => event.stopPropagation()}><span className="mobile-action-sheet__handle" /><h2>Generate tracking link</h2><label>Campaign name<input value={selected.name} readOnly /></label><label>Sub-ID<input placeholder="Optional sub-ID" /></label><button type="button" className="mobile-primary-button" onClick={() => setSelected(null)}>Create link</button></div></div>}</div>; }
