"use client"
import React, { useState } from "react"
import Userheader from '../components/Userheader'
import Userfooter from '../components/Userfooter'
import { Container, Image, Badge, Button, Modal, Form, InputGroup, Alert } from 'react-bootstrap'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faEye, faEyeSlash, } from '@fortawesome/free-solid-svg-icons';
import Link from "next/link"
import Leftsidemenu from '../components/Leftsidemenu';

const page = () => {

    const [showModal2, setShowModal2] = useState(false);
    const [showModal3, setShowModal3] = useState(false);
    const [showModal9, setShowModal9] = useState(false);
    const handleClose9 = () => setShowModal9(false);
    const handleShow9 = () => setShowModal9(true);


    const handleClose2 = () => setShowModal2(false);
    const handleShow2 = () => setShowModal2(true);

    const handleClose3 = () => setShowModal3(false);
    const handleShow3 = () => setShowModal3(true);

    const [showModal4, setShowModal4] = useState(false);
    const [showModal5, setShowModal5] = useState(false);

    const handleClose4 = () => setShowModal4(false);
    const handleShow4 = () => setShowModal4(true);

    const handleClose5 = () => setShowModal5(false);
    const handleShow5 = () => setShowModal5(true);

    return (
        <div className="pagecontent gridpagecontent innerpagegrid">
            <div className="backgroundoverlay" id="backgroundoverlay"></div>
            <Userheader />
            <Leftsidemenu />
            <div className="innerpagecontent">
                <h2 className="h2">Security Settings</h2>
            </div>
            <article className="gridparentbox">
                <Container className="sitecontainer">

                    <div className='innerpagetab boxtabb'>
                        {/* <Alert variant="warning">
                            <b>Note :</b> For your security, withdrawals will be temporarily unavaliable for 24 hours after changing security settings
                        </Alert> */}
                        <div className="securitypage">
                            <div className="securityinnerbox panelcontentbox mt-0 green-wrapper-bg">
                                <div className="">
                                    <div>
                                        <h2 className="subhead pb-2">Two-Factor Authentication (2FA)</h2>
                                        <p className="mb-3 pb-3">Two-factor authentication is an enhanced security measure. Once enabled, you will be required to give two types of identification when you log into.</p>
                                    </div>
                                    <div className="faverifybox">
                                        <div className="profiletablebox contentbox">
                                            <div> <Image className='badge-img' src="assets/images/google-sec.svg" /> </div>
                                            <div>
                                                <h4>Google Authenticator (Recommended)<span className="ms-2"><Badge className="bg-success">
                                                    <i className="fa fa-check-circle me-1"></i>Enabled</Badge></span></h4>
                                                <h5 className="t-gray">2FA code will be generated by your smartphone app "Google Authenticator" available for both iOS and Android phones.
                                                </h5>
                                            </div>
                                            <div>  <Link href="/auth" id="authbtn" className="btn sitebtn borderbtn green-btn">Enable</Link> </div>
                                        </div>
                                        <hr />

                                        <div className="profiletablebox contentbox">
                                            <div> <Image className='badge-img' src="assets/images/gmail-sec.svg" /> </div>
                                            <div>
                                                <h4>Email Verification</h4>
                                                <h5 className="t-gray">Send 2FA code via Email</h5>
                                            </div>
                                            <div><Button onClick={handleShow2} id="emailbtn" className="btn sitebtn borderbtn">Enable</Button> </div>
                                        </div>



                                    </div>
                                </div>
                            </div>
                            <div className="securityinnerbox panelcontentbox mt-3">
                                <div className="">
                                    <div>
                                        <h2 className="heading-box pt-0 mb-1 ps-0 pe-0 border-0">Advanced Settings</h2>
                                    </div>
                                    <div className="faverifybox">
                                        <div className="profiletablebox contentbox">
                                            <div> <Image className='badge-img' src="assets/images/kyc-sec.svg" /> </div>
                                            <div>
                                                <h4>KYC Verification</h4>
                                                <h5 className="t-gray">View login and security activity history.
                                                </h5>
                                            </div>
                                            <div>
                                                <Link id="kycbtn" className="btn sitebtn borderbtn" href="/kyc">View</Link>
                                            </div>
                                        </div>
                                        <hr />
                                        <div className="profiletablebox contentbox">
                                            <div> <Image className='badge-img' src="assets/images/backup-pharse-sec.svg" /> </div>
                                            <div>
                                                <h4>Backup Phrase</h4>
                                                <h5 className="t-gray">View login and security activity history.
                                                </h5>
                                            </div>
                                            <div>
                                                <Link id="recoverybtn" className="btn sitebtn borderbtn" href="/recoverykey">View</Link>
                                            </div>
                                        </div>
                                        {/* <hr /> */}
                                        {/* <div className="profiletablebox contentbox">
                                            <div> <Image className='badge-img' src="assets/images/mpin-sec.svg" /> </div>
                                            <div>
                                                <h4>MPIN </h4>
                                                <h5 className="t-gray">Your MPIN is a secure code that allows you to log in quickly and safely. Make sure to keep it confidential.
                                                </h5>
                                            </div>
                                            <div> <Button onClick={handleShow4} id="mpinbtn" className="btn sitebtn borderbtn green-btn">
                                                Change
                                            </Button> </div>
                                        </div> */}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </Container>
            </article>
            <Userfooter />


            <Modal show={showModal2} onHide={handleClose2} className='modalbgt authmodal' aria-labelledby="contained-modal-title-vcenter"
                centered>
                <Modal.Header closeButton>
                    <Modal.Title id="contained-modal-title-vcenter">
                        Email Verification
                    </Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <Form className='siteformbg'>
                        <Alert variant="warning">
                            Please enter the 6-digit verification code that was sent to john@mailinator.com
                        </Alert>
                        <Form.Group className="form-group" controlId="exampleForm.ControlInput2">
                            <Form.Label>Enter Verification Code</Form.Label>
                            <InputGroup className="mb-3">
                                <Form.Control name="code" id="enterverificationcode" type="text" />
                                <InputGroup.Text id="emailcode">Get Code</InputGroup.Text>
                            </InputGroup>
                        </Form.Group>
                        <div className="mt-3">
                            <Link href="" className="btn sitebtn w-100" id="confirm">Submit</Link>
                        </div>
                        <div className="mt-3"><p className="content">Mail not received click resend link, <span className="alink">Send code</span></p></div>
                    </Form>
                </Modal.Body>
            </Modal>

            {/* Phone Number  */}
            <Modal show={showModal4} onHide={handleClose4} className='modalbgt authmodal' aria-labelledby="contained-modal-title-vcenter" centered>
                <Modal.Header closeButton>
                    <Modal.Title>
                        Change MPIN
                    </Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <Form className='siteformbg'>
                        <Form.Group className="form-group" controlId="exampleForm.ControlInput2">
                            <Form.Label>Old MPIN</Form.Label>
                            <Form.Control name="code" id="oldmpin" type="text" />
                        </Form.Group>
                        <Form.Group className="form-group" controlId="exampleForm.ControlInput2">
                            <Form.Label>New MPIN</Form.Label>
                            <Form.Control name="code" id="newmpin" type="text" />
                        </Form.Group>
                        <Form.Group className="form-group" controlId="exampleForm.ControlInput2">
                            <Form.Label>Current MPIN</Form.Label>
                            <Form.Control name="code" id="currentmpin" type="text" />
                        </Form.Group>
                        <div className="d-flex gap-2 mt-3">
                            <Button type="button" className="borderbtn" data-bs-dismiss="modal">Cancel</Button>
                            <Link href="" className="btn sitebtn" onClick={() => { handleClose4(); handleShow5(); }}>Confirm</Link>
                        </div>
                    </Form>
                </Modal.Body>
            </Modal>
            <Modal show={showModal5} onHide={handleClose5} className='modalbgt authmodal' aria-labelledby="contained-modal-title-vcenter" centered>
                <Modal.Header closeButton>
                    <Modal.Title id="contained-modal-title-vcenter">
                        Add Phone Number
                    </Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <Form className='siteformbg'>
                        <Alert variant="warning">
                            <b>Note :</b>For your security, withdrawals will be temporarily unavaliable for 24 hours after changing security settings
                        </Alert>
                        <Form.Group className="form-group" controlId="exampleForm.ControlInput2">
                            <Form.Label>Enter Verification Code</Form.Label>
                            <InputGroup className="mb-3">
                                <InputGroup.Text id="basic-addon2">+91</InputGroup.Text>
                                <Form.Control name="code" id="verificode" />
                            </InputGroup>
                        </Form.Group>
                        <Form.Group className="form-group" controlId="exampleForm.ControlInput2">
                            <Form.Label>Enter SMS Verification Code</Form.Label>
                            <InputGroup className="mb-3">
                                <Form.Control name="code" id="smscode" type="text" />
                                <InputGroup.Text id="basic-addon2">Get Code</InputGroup.Text>
                            </InputGroup>
                        </Form.Group>
                        <div className="d-flex gap-2 mt-3">
                            <Button type="button" className="borderbtn" data-bs-dismiss="modal">Cancel</Button>
                            <Link href="" className="btn sitebtn" id="confirm">Confirm</Link>
                        </div>
                    </Form>
                </Modal.Body>
            </Modal>

        </div>

    )
}

export default page