"use client";
import React, { useState } from "react";
import Userheader from "./Userheader";
import MobileBottomNav from "./MobileBottomNav";

const records = [{ id: "TXN-24646", title: "BTC deposit", date: "18 May 2026", amount: "+$150.00", status: "Completed" }, { id: "TXN-24647", title: "ETH deposit", date: "16 May 2026", amount: "+$80.00", status: "Pending" }];
export default function MobileUtilitySurface({ title, mode }) {
  const [sheet, setSheet] = useState(false);
  const [sent, setSent] = useState(false);
  const isHistory = mode === "deposithistory";
  const isMoney = ["deposit", "fiatdeposit", "fiatwithdraw"].includes(mode);
  const isForm = ["contactus", "feedback", "forgot", "disputetrade"].includes(mode);
  return <div className={`pagecontent gridpagecontent innerpagegrid dashboardpage mobile-utility-page mobile-utility-page--${mode}`}><Userheader /><main className="mobile-utility-page__main"><div className="mobile-page-heading"><span>{mode === "kyc" || mode === "kycview" ? "Account verification" : "Account workspace"}</span><h1>{title}</h1><p>{descriptionFor(mode)}</p></div>{mode === "chat" && <ChatContent />}{isHistory && <HistoryContent />}{isMoney && <MoneyContent mode={mode} onSubmit={() => setSheet(true)} />}{isForm && <FormContent mode={mode} onSubmit={() => { setSent(true); setSheet(true); }} />}{(mode === "kyc" || mode === "kycview") && <KycContent mode={mode} onSubmit={() => setSheet(true)} />}</main><MobileBottomNav />{sheet && <div className="mobile-action-sheet" onClick={() => setSheet(false)}><div onClick={(event) => event.stopPropagation()}><span className="mobile-action-sheet__handle" /><h2>{sent ? "Message sent" : mode === "kycview" ? "Verification submitted" : "Request received"}</h2><p>{sent ? "Our support team will get back to you shortly." : "Your information has been saved for review."}</p><button type="button" className="mobile-primary-button" onClick={() => setSheet(false)}>Done</button></div></div>}</div>;
}
function descriptionFor(mode) { const descriptions = { chat: "Keep conversations and trade updates in one place.", contactus: "Tell us what you need help with.", deposit: "Add funds to your wallet securely.", deposithistory: "Review your recent wallet deposits.", disputetrade: "Raise a clear issue about a trade.", feedback: "Help us improve your experience.", fiatdeposit: "Deposit fiat currency through your preferred method.", fiatwithdraw: "Withdraw fiat currency to a verified account.", forgot: "Recover access to your account securely.", kyc: "Complete verification to unlock account features.", kycview: "Review your verification status and documents." }; return descriptions[mode] || "Manage your account with simple, focused controls."; }
function ChatContent() { return <section className="mobile-chat-list">{["John · Trade #24646", "Support team", "William · Payment request"].map((item, index) => <article key={item}><div className="mobile-chat-avatar">{index === 1 ? "S" : "J"}</div><div><strong>{item}</strong><span>{index === 1 ? "We have received your request." : "Your trade update is ready to view."}</span></div><b>{index === 0 ? "2m" : "Today"}</b></article>)}<button type="button" className="mobile-primary-button">Start new conversation</button></section>; }
function HistoryContent() { return <section className="mobile-history-list"><div className="mobile-filter-row"><input type="date" aria-label="From date" /><input type="date" aria-label="To date" /></div>{records.map((record) => <article key={record.id}><div><strong>{record.title}</strong><span>{record.id} · {record.date}</span></div><b className={record.status === "Pending" ? "is-pending" : ""}>{record.status}</b><strong className="mobile-history-amount">{record.amount}</strong></article>)}</section>; }
function MoneyContent({ mode, onSubmit }) { const withdraw = mode === "fiatwithdraw"; return <section className="mobile-utility-card"><h2>{withdraw ? "Withdraw funds" : "Deposit funds"}</h2><div className="mobile-form-grid"><label>{withdraw ? "Bank account" : "Deposit method"}<select><option>{withdraw ? "USD · •••• 4567" : "Bank transfer"}</option><option>Card</option></select></label><label>Amount<input inputMode="decimal" placeholder={withdraw ? "$100" : "$250"} /></label><label>Currency<select><option>USD</option><option>EUR</option></select></label><label>Reference<input placeholder="Optional reference" /></label></div><button type="button" className="mobile-primary-button" onClick={onSubmit}>{withdraw ? "Request withdrawal" : "Continue"}</button></section>; }
function FormContent({ mode, onSubmit }) { const forgot = mode === "forgot"; return <section className="mobile-utility-card"><h2>{forgot ? "Find your account" : mode === "feedback" ? "Share feedback" : mode === "disputetrade" ? "Trade dispute" : "Contact support"}</h2><div className="mobile-form-grid">{!forgot && <label>Subject<input placeholder={mode === "feedback" ? "What can we improve?" : "How can we help?"} /></label>}<label>{forgot ? "Email address" : "Message"}{forgot ? <input type="email" placeholder="you@example.com" /> : <textarea rows="5" placeholder="Write your message" />}</label>{mode === "disputetrade" && <label>Trade ID<input placeholder="TRD-24646" /></label>}{mode === "feedback" && <label>Rating<select><option>5 - Excellent</option><option>4 - Good</option><option>3 - Average</option></select></label>}</div><button type="button" className="mobile-primary-button" onClick={onSubmit}>{forgot ? "Send recovery link" : "Submit"}</button></section>; }
function KycContent({ mode, onSubmit }) { const review = mode === "kycview"; return <section className="mobile-kyc-flow"><div className="mobile-kyc-status"><strong>{review ? "Under review" : "Verification checklist"}</strong><span>{review ? "Submitted 18 May 2026" : "2 of 4 steps completed"}</span></div>{["Personal details", "Identity document", "Proof of address", "Review and submit"].map((step, index) => <article key={step} className={index < (review ? 4 : 2) ? "is-done" : ""}><b>{index < (review ? 4 : 2) ? "✓" : index + 1}</b><div><strong>{step}</strong><span>{index < 2 ? "Information added" : "Required to continue"}</span></div>{!review && index === 1 && <button type="button" onClick={onSubmit}>Upload</button>}</article>)}{review && <button type="button" className="mobile-primary-button" onClick={onSubmit}>View submitted documents</button>}</section>; }
